name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build packages
      run: bash build.sh
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: mpv
